name: SSH Access Test Version 2.2

on: [push]

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Output SSH Key
        env:
          DEPLOYUSERSSHKEY: ${{ secrets.SSHKEY }}
        run: |
          echo "SSH Key:"
          echo ${{ secrets.SSHKEY }
      
      - name: Test SSH Connection and Execute whoami
        env:
          DEPLOYUSERSSHKEY: ${{ secrets.SSHKEY }}
        run: |
          echo "$DEPLOYUSERSSHKEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin deployuser@35.86.119.51 whoami
