name: Print SSH Key for Debugging

on: [push]

jobs:
  print-ssh-key:
    runs-on: ubuntu-latest

    steps:
      - name: Print SSH Key
        env:
          DEPLOYUSERSSHKEY: ${{ secrets.SSHKEY }}
        run: |
          echo "Starting to print SSH Key..."
          echo "$DEPLOYUSERSSHKEY"
          echo "Finished printing SSH Key."
