name: SSH Access Test Version 2.3

on: [push]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    environment: enviro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Output SSH Key
        run: |
          echo "SSH Key:"
          echo "${{ secrets.KEY }}"

      - name: Test SSH Connection and Execute whoami
        run: |
          echo "${{ secrets.KEY }}" | ssh -o StrictHostKeyChecking=no -i /dev/stdin deployuser@35.86.119.51 whoami
