name: SSH Access Test Version 2.3

on: [push]

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        env:
          DEPLOYUSERSSHKEY: ${{ secrets.SSHKEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOYUSERSSHKEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
      
      - name: Test SSH Connection and Execute whoami
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa deployuser@35.86.119.51 whoami
